AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS API Gateway with a Mock Integration

Resources:

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: An API Gateway with a Mock Integration
      EndpointConfiguration:
        Types:
          - EDGE
      Name: mock-api

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: 'portfolio'
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: true
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        IntegrationResponses:
          - ResponseTemplates:
              application/json: "{\"portfolioData\":[{\"id\": 123,\"numberOfShares\": 12,\"status\": \"DOCUSIGN_NEEDED\"},{\"id\": 456,\"numberOfShares\": 1,\"status\": \"OWNED\"}]}"
            SelectionPattern: '2\d{2}'
            StatusCode: 200
            ResponseParameters: 
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date, x-api-key''' 
              method.response.header.Access-Control-Allow-Methods: '''GET''' 
              method.response.header.Access-Control-Allow-Origin: '''*'''
          - ResponseTemplates:
              application/json: "{\"message\": \"Internal Server Error\"}"
            SelectionPattern: '5\d{2}'
            StatusCode: 500
        RequestTemplates:
          "application/json": "{\n \"statusCode\": 200\n}"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        # RequestTemplates:
        #   application/json: "{\"statusCode\": $input.json('$.statusCode'), \"message\": $input.json('$.message')}"
        Type: MOCK
        TimeoutInMillis: 29000
      MethodResponses:
        - ResponseModels:
            application/json: !Ref ApiGatewayModel
          StatusCode: 200
          ResponseParameters: 
            method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date, x-api-key''' 
            method.response.header.Access-Control-Allow-Methods: '''GET''' 
            method.response.header.Access-Control-Allow-Origin: '''*'''
      RequestParameters:
        method.request.header.x-api-key: true
      OperationName: 'mock'
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi
  
  ApiGatewayCORS:
    # Conditon: EnableCors
    Type: AWS::ApiGateway::Method
    DependsOn: ApiGatewayMethod
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        ConnectionType: INTERNET
        IntegrationResponses:
        - StatusCode: '200'
          ResponseParameters: 
            method.response.header.Access-Control-Allow-Headers: '''Content-Type, X-Amz-Date, x-api-key'''
            method.response.header.Access-Control-Allow-Methods: '''OPTIONS, GET'''
            method.response.header.Access-Control-Allow-Origin: '''*'''
          ResponseTemplates: 
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          "application/json": "{\n \"statusCode\": 200\n}"
        TimeoutInMillis: 2900
        Type: MOCK
      MethodResponses:
      - StatusCode: '200'
        ResponseModels: 
          application/json: 'Empty' 
        ResponseParameters: 
          method.response.header.Access-Control-Allow-Headers: false 
          method.response.header.Access-Control-Allow-Methods: false 
          method.response.header.Access-Control-Allow-Origin: false
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayDataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: 'data'
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayDataMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        IntegrationResponses:
          - ResponseTemplates:
              application/json: "{\"data\": {\"sharesAvailable\":200,\"date\":1633669106301}}"
            SelectionPattern: '2\d{2}'
            StatusCode: 200
          - ResponseTemplates:
              application/json: "{\"message\": \"Internal Server Error\"}"
            SelectionPattern: '5\d{2}'
            StatusCode: 500
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: "{\"statusCode\": 200}"
        Type: MOCK
        TimeoutInMillis: 29000
      MethodResponses:
        - ResponseModels:
            application/json: !Ref ApiGatewayModel
          StatusCode: 200
        - ResponseModels:
            application/json: !Ref ApiGatewayModel
          StatusCode: 500
      OperationName: 'mock'
      ResourceId: !Ref ApiGatewayDataResource
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref ApiGatewayRestApi
      Schema: {}

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      Description: Mock API Stage v0
      RestApiId: !Ref ApiGatewayRestApi
      StageName: 'v0'

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      Description: Mock API Deployment
      RestApiId: !Ref ApiGatewayRestApi
  


Outputs:
  GatewayEndpoint:
    Description: Endpoint for Gateway
    Value: !Sub 'https://${ApiGatewayRestApi.RootResourceId}.execute-api.us-east-1.amazonaws.com/v0'